--remote
local args = {
	buffer.fromstring("\t\016\000IronHeart Sect 1")
}
game:GetService("ReplicatedStorage"):WaitForChild("ByteNetReliable"):FireServer(unpack(args))

--function
-- Calling function info
-- Generated by the SimpleSpy V3 serializer

local functionInfo = {
    ["script"] = {
        ["SourceScript"] = game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("_Index"):WaitForChild("ffrostflame_bytenet@0.4.6"):WaitForChild("bytenet"):WaitForChild("process"):WaitForChild("client"),
        ["CallingScript"] = game:GetService("ReplicatedStorage"):WaitForChild("Packages"):WaitForChild("_Index"):WaitForChild("ffrostflame_bytenet@0.4.6"):WaitForChild("bytenet")
    },
    ["upvalues"] = {
        [1] = {
            ["size"] = 256,
            ["references"] = {},
            ["cursor"] = 0,
            ["buff"] = buffer(buffer: 0x0000000034e69617) --[[Generation Failure]]
        },
        [2] = game:GetService("ReplicatedStorage"):WaitForChild("ByteNetReliable"),
        [3] = {
            ["size"] = 256,
            ["references"] = {},
            ["cursor"] = 0,
            ["buff"] = buffer(buffer: 0x00000000e7ab3f97) --[[Generation Failure]]
        },
        [4] = game:GetService("ReplicatedStorage"):WaitForChild("ByteNetUnreliable")
    },
    ["info"] = {
        ["source"] = "=ReplicatedStorage.Packages._Index.ffrostflame_bytenet@0.4.6.bytenet.process.client",
        ["what"] = "Lua",
        ["numparams"] = 0,
        ["func"] = function: 0x000000001cfd9ad7,
        ["short_src"] = "ReplicatedStorage.Packages._Index.ffrostflame_bytenet@0.4.6.bytenet.process.client",
        ["currentline"] = 54,
        ["name"] = "",
        ["is_vararg"] = 0,
        ["nups"] = 4
    },
    ["constants"] = {
        [1] = "cursor",
        [2] = "buffer",
        [3] = "create",
        [5] = "copy",
        [7] = "buff",
        [8] = "references",
        [9] = "FireServer",
        [10] = "table",
        [11] = "clear"
    }
}

--